// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXdjQ5U_6RhdHOw1d_MqMTmCrod1cXxzk',
    appId: '1:282975731239:web:0ffb223784ab092ffb9802',
    messagingSenderId: '282975731239',
    projectId: 'flutter-expert-7e356',
    authDomain: 'flutter-expert-7e356.firebaseapp.com',
    storageBucket: 'flutter-expert-7e356.appspot.com',
    measurementId: 'G-HSGTC245VB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2x5PQvCtrrz8BXcfidwSpg6VsFmzpVOg',
    appId: '1:282975731239:android:71d5e1e9c034d06ffb9802',
    messagingSenderId: '282975731239',
    projectId: 'flutter-expert-7e356',
    storageBucket: 'flutter-expert-7e356.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcSYGV9E2l1Gy4OrFIXUfkFPfVKs_IN6o',
    appId: '1:282975731239:ios:90c465dc1e2e7570fb9802',
    messagingSenderId: '282975731239',
    projectId: 'flutter-expert-7e356',
    storageBucket: 'flutter-expert-7e356.appspot.com',
    iosClientId: '282975731239-9ek2a7u9ck13vqg4m1uf44n6fhe433o6.apps.googleusercontent.com',
    iosBundleId: 'com.dicoding.ditonton',
  );
}
